"""<my last revision>

Revision ID: 2216690fd2b2
Revises: 29a12367aa61
Create Date: 2023-10-07 10:39:42.778711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2216690fd2b2'
down_revision = '29a12367aa61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_task_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
