"""<third revision>

Revision ID: 29a12367aa61
Revises: 819fbfd7039e
Create Date: 2023-10-07 10:28:44.235379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a12367aa61'
down_revision = '819fbfd7039e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('due_date')
        batch_op.drop_column('completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
