"""second revison

Revision ID: 819fbfd7039e
Revises: 31aabbf7afc5
Create Date: 2023-10-07 08:09:01.842025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819fbfd7039e'
down_revision = '31aabbf7afc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_task_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_task_association',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('task_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='fk_user_task_association_task_id_task'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_task_association_user_id_user')
    )
    # ### end Alembic commands ###
